### ISSUE TITLE
hello 你好 有没有这个的视频课程可以分享一下呀？非常感谢～

### ISSUE THREAD

**Issue by ChenMolu** [killstealing/lmy-live-app#5]

**Comment by Quan-Mou** [comment]
我有

**Comment by killstealing** [comment]
我有前7章的，后面的没有了，你有后面的吗

> 我有

**Comment by Quan-Mou** [comment]
> 我有前7章的，后面的没有了，你有后面的吗
> 
> > 我有

我也是只有前七章的，但是没有课件，那些课件还要手动的去补全，大佬有课件嘛

**Comment by Quan-Mou** [comment]
> 我有前7章的，后面的没有了，你有后面的吗
> 
> > 我有

我后面应该会买，你要不要

**Comment by killstealing** [comment]
你看看这个 
https://pan.baidu.com/s/1MKgFpoAEYB1smOdn2d4rKg?pwd=ki8n

**Comment by killstealing** [comment]
> > 我有前7章的，后面的没有了，你有后面的吗
> > > 我有
> 
> 我后面应该会买，你要不要



> > 我有前7章的，后面的没有了，你有后面的吗
> > > 我有
> 
> 我也是只有前七章的，但是没有课件，那些课件还要手动的去补全，大佬有课件嘛



> > 我有前7章的，后面的没有了，你有后面的吗
> > > 我有
> 
> 我后面应该会买，你要不要

要啊，买完分享一下，别是那种加密的视频，那种好像只能一个机器看

**Comment by ChenMolu** [comment]
我也是只有前七章的 要不大家一起拼着买一下？

**Comment by Quan-Mou** [comment]
> 我也是只有前七章的 要不大家一起拼着买一下？

我觉得OK

**Comment by ChenMolu** [comment]
> > 我也是只有前七章的 要不大家一起拼着买一下？
> 
> 我觉得OK

我的微信 CLuhua_17

**Comment by Guoxingt** [comment]
> > 我有前7章的，后面的没有了，你有后面的吗
> > > 我有
> 
> 我后面应该会买，你要不要

大佬我也要买，可以卖我一份吗
